eshop_site/core/urls.py
from django.urls import path
from .views import HomeView, ItemDetailView, add_to_cart, remove_from_cart, OrderSummaryView, add_quantity, minus_quantity, delete_from_order, CheckoutView, PaymentView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('add-quantity/<slug>/', add_quantity, name='add-quantity'),
    path('minus-quantity/<slug>/', minus_quantity, name='minus-quantity'),
    path('delete-from-order/<slug>/', delete_from_order, name='delete-from-order'),
    path('payment/', PaymentView.as_view(), name='payment')
]

eshop_site/eshop_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include(('core.urls', 'core'), namespace='core')),
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eshop_site/core/models.py
from django.conf import settings
from django.db import models
from django.shortcuts import reverse
from django_countries.fields import CountryField

CATEGORY_CHOICES = (
    ('S', 'Футболки'),
    ('H', 'Толстовки'),
    ('B', 'Рюкзаки')
)

LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger')
)


class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    slug = models.SlugField()
    description = models.TextField()
    image = models.ImageField(blank=True, null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:product", kwargs={
            'slug': self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={
            'slug': self.slug
        })

    def remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={
            'slug': self.slug
        })


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.item.price * self.quantity

    def get_total_discount_item_price(self):
        return self.item.discount_price * self.quantity

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    address = models.ForeignKey('Address', on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for item in self.items.all():
            total += item.get_final_price()
        return total


class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    countries = CountryField(multiple=False)
    zip = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username

eshop_site/core/forms.py
from django import forms
from django_countries.fields import CountryField
from django.forms import ModelForm
from .models import Item


PAYMENT_CHOICES = (
    ('B', 'Банковская карта'),
    ('N', 'Наличные')
)


class CheckOutForm(forms.Form):
    street_address = forms.CharField(label='Адрес', widget=forms.TextInput(attrs={'placeholder': 'Ул. Лубянка д.5'}))
    country = CountryField(blank_label='select country').formfield()
    zip = forms.CharField(label='Почтовый индекс')
    payment_option = forms.ChoiceField(label='Способ оплаты', widget=forms.RadioSelect, choices=PAYMENT_CHOICES)


class CategoryForm(ModelForm):
    class Meta:
        model = Item
        fields = ['category']

eshop_site/core/views.py
import requests
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DetailView, View
from .models import Item, OrderItem, Order, Address
from django.utils import timezone
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from .forms import CheckOutForm, CategoryForm
from django.db.models import Count
from allauth.account.decorators import login_required


class HomeView(ListView):
    model = Item
    template_name = "home-page.html"
    paginate_by = 5

    def get_queryset(self):
        category = self.request.GET.get('category')
        if category:
            return Item.objects.filter(category=category)
        else:
            return Item.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        context['categories'] = self.get_unique_categories()
        return context

    @staticmethod
    def get_unique_categories():
        items = Item.objects.all()
        categories = []
        for item in items:
            if item.category not in categories:
                categories.append((item.category, item.get_category_display))
        return categories

    # TODO сделать категории фильтр
    # TODO настроить систему оплаты


class OrderSummaryView(View):
    def get(self, *args, **kwargs):
        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
            context = {
                'objects': order
            }
            return render(self.request, 'order_summary.html', context)
        except ObjectDoesNotExist:
            messages.error(self.request, "У вас нету активного заказа")
            return redirect("/")


class ItemDetailView(DetailView):
    model = Item
    template_name = "product.html"


class PaymentView(View):
    def get(self, *args, **kwargs):
        return render(self.request, 'payment.html')


class CheckoutView(View):
    def get(self, *args, **kwargs):
        form = CheckOutForm()
        order = Order.objects.get(user=self.request.user, ordered=False)
        context = {
            'form': form,
            'order': order
        }
        return render(self.request, 'checkout-page.html', context)

    def post(self, *args, **kwargs):
        form = CheckOutForm(self.request.POST or None)
        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
            if form.is_valid():
                print(form.cleaned_data)
                street_address = form.cleaned_data.get('street_address')
                country = form.cleaned_data.get('country')
                zip = form.cleaned_data.get('zip')
                payment_option = form.cleaned_data.get('payment_option')
                address = Address.objects.create(
                    user=self.request.user,
                    street_address=street_address,
                    countries=country,
                    zip=zip
                )
                order.address = address
                order.save()
                if payment_option == 'N':
                    messages.info(self.request, 'Ваш заказ был создан. Ждите звонка от оператора')
                    return redirect('/')
                # TODO настроить Юкассу
                if payment_option == 'B':
                    messages.warning(self.request, 'Выберите другой метод оплаты')
                    return redirect('core:checkout')
            messages.warning(self.request, 'Ошибка оплаты')
            return redirect('core:checkout')
        except ObjectDoesNotExist:
            messages.error(self.request, "У вас нету активного заказа")
            return redirect("/")


@login_required
def add_to_cart(request, slug):
    item = get_object_or_404(Item, slug=slug)
    order_item, created = OrderItem.objects.get_or_create(
        item=item,
        user=request.user,
        ordered=False
    )
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        # Если товар есть в заказе - добавляем еще один экземпляр
        if order.items.filter(item__slug=item.slug).exists():
            order_item.quantity += 1
            order_item.save()
            messages.info(request, "Количество товара в корзине было обновлено")
        # Если товара не было - просто добавляем его
        else:
            messages.info(request, "Товар был добавлен в корзину")
            order.items.add(order_item)
    else:
        ordered_date = timezone.now()
        order = Order.objects.create(user=request.user, ordered_date=ordered_date)
        order.items.add(order_item)
        messages.info(request, "Товар был добавлен в корзину")
    return redirect("core:product", slug=slug)


def remove_from_cart(request, slug):
    item = get_object_or_404(Item, slug=slug)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.items.filter(item__slug=item.slug).exists():
            order_item = OrderItem.objects.filter(item=item, user=request.user, ordered=False)[0]
            order.items.remove(order_item)
            messages.info(request, "Товар был удален из корзины")
            return redirect("core:product", slug=slug)
        else:
            messages.info(request, "Товара не было в корзине")
            return redirect("core:product", slug=slug)
    else:
        messages.info(request, "Вам нужно создать заказ")
        return redirect("core:product", slug=slug)


def add_quantity(request, slug):
    item = OrderItem.objects.get(user=request.user, item__slug=slug)
    item.quantity += 1
    item.save()
    return redirect("core:order-summary")


def minus_quantity(request, slug):
    item = OrderItem.objects.get(user=request.user, item__slug=slug)
    item.quantity -= 1
    item.save()
    return redirect("core:order-summary")


def delete_from_order(request, slug):
    order_item = OrderItem.objects.get(user=request.user, item__slug=slug)
    order = Order.objects.get(user=request.user, ordered=False)
    order.items.remove(order_item)
    return redirect("core:order-summary")

eshop_site/core/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block head_title %}{% endblock %}</title>
  {% block extra_head %}
  {% endblock %}
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

  </style>
</head>

{% include "navbar.html" %}

<body>

    <div class="mt-5 pt-4">
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endfor %}
    {% endif %}
    </div>

    {% block content %}
    {% endblock content %}

    {% block extra_body %}
    {% endblock %}

    {% include "footer.html" %}
    {% include "scripts.html" %}

</body>
</html>

eshop_site/core/templates/checkout-page.html
{% extends "base.html" %}
{% block content %}
{% load crispy_forms_tags %}


<body class="grey lighten-3">

  <!--Main layout-->
  <main>
    <div class="container wow fadeIn">

      <!-- Heading -->
      <h2 class="my-5 h2 text-center">Оформление заказа</h2>

      <!--Grid row-->
      <div class="row">

        <!--Grid column-->
        <div class="col-md-8 mb-4">

          <!--Card-->
          <div class="card">

            <form method="POST" class="card-body md-5">
              {% csrf_token %}
              {{ form|crispy }}
              <hr class="mb-4">
              <button class="btn btn-primary btn-lg btn-block" type="submit">Перейти к оплате</button>
            </form>


            </form>

          </div>
          <!--/.Card-->

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-4 mb-4">

          <!-- Heading -->
          <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-muted">Ваша корзина</span>
            <span class="badge badge-secondary badge-pill">{{ order.items.count }}</span>
          </h4>

          <!-- Cart -->
          <ul class="list-group mb-3 z-depth-1">
            {% for order_item in order.items.all %}
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">{{ order_item.item.title }}</h6>
                <small class="text-muted">{{order_item.item.description}}</small>
              </div>
              {% if order_item.item.discount_price %}
              <span class="text-muted">${{ order_item.item.discount_price }}</span>
              {% else %}
              <span class="text-muted">${{ order_item.item.price }}</span>
              {% endif %}
            </li>
            {% endfor %}

            <li class="list-group-item d-flex justify-content-between">
              <span>Суммарная цена</span>
              <strong>{{ order.get_total }}</strong>
            </li>
          </ul>
          <!-- Cart -->

          <!-- Promo code -->
          <form class="card p-2">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Промо код" aria-label="Recipient's username" aria-describedby="basic-addon2">
              <div class="input-group-append">
                <button class="btn btn-secondary btn-md waves-effect m-0" type="button">Применить</button>
              </div>
            </div>
          </form>
          <!-- Promo code -->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->
</body>



{% endblock content %}

eshop_site/core/templates/footer.html
  <!--Footer-->
  <footer class="page-footer text-center font-small mt-4 wow fadeIn">


    <hr class="my-4">

    <!-- Social icons -->
    <div class="pb-4">
      <a href="https://www.facebook.com/mdbootstrap" target="_blank">
        <i class="fab fa-facebook-f mr-3"></i>
      </a>

      <a href="https://twitter.com/MDBootstrap" target="_blank">
        <i class="fab fa-twitter mr-3"></i>
      </a>

      <a href="https://www.youtube.com/watch?v=7MUISDJ5ZZ4" target="_blank">
        <i class="fab fa-youtube mr-3"></i>
      </a>

      <a href="https://plus.google.com/u/0/b/107863090883699620484" target="_blank">
        <i class="fab fa-google-plus-g mr-3"></i>
      </a>

      <a href="https://dribbble.com/mdbootstrap" target="_blank">
        <i class="fab fa-dribbble mr-3"></i>
      </a>

      <a href="https://pinterest.com/mdbootstrap" target="_blank">
        <i class="fab fa-pinterest mr-3"></i>
      </a>

      <a href="https://github.com/mdbootstrap/bootstrap-material-design" target="_blank">
        <i class="fab fa-github mr-3"></i>
      </a>

      <a href="http://codepen.io/mdbootstrap/" target="_blank">
        <i class="fab fa-codepen mr-3"></i>
      </a>
    </div>
    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright py-3">
      © 2022 Copyright:
      <a href="https://mdbootstrap.com/education/bootstrap/" target="_blank"> D I C K O M R A Z </a>
    </div>
    <!--/.Copyright-->

  </footer>
  <!--/.Footer-->

eshop_site/core/templates/home-page.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}


<body>

  <!--Main layout-->
  <main>
    <div class="container">

      <!--Navbar-->
      <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

        <!-- Navbar brand -->
        <span class="navbar-brand">Категории:</span>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
          aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">
          <!-- Links -->
          <ul class="navbar-nav mr-auto">
            {% if request.get_full_path == '/' %}
            <li class="nav-item active">
              <a class="nav-link" href="/">Все
                <span class="sr-only">(current)</span>
              </a>
              {% else %}
              <li class="nav-item">
              <a class="nav-link" href="/">Все
                <span class="sr-only">(current)</span>
              </a>
            {% endif %}
            </li>
            {% for category in categories %}
            {% if request.get_full_path == '/?category={{category.0}}' %}
            {{ category.0 }}
            <li class="nav-item active">
              <span class="sr-only">(current)</span>
              <a class="nav-link" href="/?category={{ category.0 }}">{{ category.1 }}</a>
            </li>
            {% else %}
            <li class="nav-item">
              <span class="sr-only">(current)</span>
              <a class="nav-link" href="/?category={{ category.0 }}">{{ category.1 }}</a>
            </li>
            {% endif %}
            {% endfor %}

          </ul>
          <!-- Links -->
<!--          <form class="form-inline">-->
<!--            <div class="md-form my-0">-->
<!--              <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">-->
<!--            </div>-->
<!--          </form>-->
        </div>
        <!-- Collapsible content -->

      </nav>
      <!--/.Navbar-->

      <!--Section: Products v.3-->
      <section class="text-center mb-4">

        <!--Grid row-->
        <div class="row wow fadeIn">

          {% for item in page_obj %}
          <div class="col-lg-3 col-md-6 mb-4">

            <!--Card-->
            <div class="card">

              <!--Card image-->
              {% if item.image %}
              <div class="view overlay">
                <img src={{ item.image.url }} class="card-img-top"
                  alt="">
                <a href="{{ item.get_absolute_url }}">
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>
              {% endif %}
              <!--Card image-->

              <!--Card content-->
              <div class="card-body text-center">
                <!--Category & Title-->
                <a href="" class="grey-text">
                  <h5>{{ item.get_category_display }}</h5>
                </a>
                {% if item.get_label_display == 'primary' %}
                <h5>
                  <strong>
                    <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title }}
                      <span class="badge badge-pill {{ item.get_label_display }}-color">NEW</span>
                    </a>
                  </strong>
                </h5>
                {% endif %}

                <h4 class="font-weight-bold blue-text">
                  <strong>
                    {% if item.discount_price %}
                    ₽{{ item.discount_price }}
                    {% else %}
                    ₽{{ item.price }}
                    {% endif %}
                  </strong>
                </h4>

              </div>
              <!--Card content-->

            </div>
            <!--Card-->

          </div>
          {% endfor %}

        </div>
        <!--Grid row-->

      </section>
      <!--Section: Products v.3-->

      <!--Pagination-->
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">
          {% if page_obj.has_previous %}
          <!--Arrow left-->
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
          {% endif %}

          {% for p in paginator.page_range %}
          {% if page_obj.number == p %}
          <li class="page-item active">
          <a class="page-link" href="?page={{ p }}">{{ p }} <span class="sr-only">(current)</span></a>
          {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ p }}">{{ p }}
            </a>
          </li>
          {% endif %}
          {% endfor %}
          {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
          {% endif %}
        </ul>
      </nav>
      <!--Pagination-->

    </div>
  </main>
  <!--Main layout-->
</body>

{% endblock content %}

eshop_site/core/templates/navbar.html
{% load cart_template_tags %}

<!-- Navbar -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">

      <!-- Brand -->
      <a class="navbar-brand waves-effect" href="/" target="_blank">
        <strong class="blue-text">D I C K O M R A Z</strong>
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        <ul class="navbar-nav mr-auto">
<!--          <li class="nav-item active">-->
<!--            <a class="nav-link waves-effect" href="/">Home-->
<!--              <span class="sr-only">(current)</span>-->
<!--            </a>-->
<!--          </li>-->
<!--          <li class="nav-item">-->
<!--            <a class="nav-link waves-effect" href="/checkout/" target="_blank">Checkout</a>-->
<!--          </li>-->
        </ul>

        <!-- Right -->
        <ul class="navbar-nav nav-flex-icons">
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a href="{% url 'core:order-summary' %}" class="nav-link waves-effect">
              <span class="badge red z-depth-1 mr-1"> {{ request.user|cart_item_count }} </span>
              <i class="fas fa-shopping-cart"></i>
              <span class="clearfix d-none d-sm-inline-block"> Корзина </span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_logout' %}">
              <span class="clearfix d-none d-sm-inline-block"> Выйти </span>
            </a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_login' %}">
              <span class="clearfix d-none d-sm-inline-block"> Зайти </span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{%url 'account_signup' %}">
              <span class="clearfix d-none d-sm-inline-block"> Зарегистрироваться </span>
            </a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
  <!-- Navbar -->

eshop_site/core/templates/order_summary.html
{% extends "base.html" %}

{% block content %}


<body>

  <!--Main layout-->
  <main>
    <div class="container">
{% if objects.items.all %}
      <h1>Заказ</h1>
<div class="table-responsive">
<table class="table table-bordered">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Наименование</th>
      <th scope="col">Цена</th>
      <th scope="col">Количество</th>
      <th scope="col">Итоговая цена</th>
    </tr>
  </thead>
  <tbody>
  {% for order_item in objects.items.all %}
  {% if order_item.quantity > 0 %}
    <tr>
      <th scope="col">{{ forloop.counter }}</th>
      <th scope="row">{{ order_item.item.title }}</th>
      <td>₽{{ order_item.item.price }}</td>
      <td>{{ order_item.quantity }} <a href="{% url 'core:add-quantity' order_item.item.slug %}">
          <i class="fas fa-plus"></i>
      </a>
        {% if order_item.quantity > 1 %}
      <a href="{% url 'core:minus-quantity' order_item.item.slug %}">
        <i class="fas fa-minus"></i>
        {% endif %}
        <a href="{% url 'core:delete-from-order' order_item.item.slug %}">
        <button type="button" class="btn btn-secondary btn-sm">Убрать из корзины</button>


      </td>
      {% if order_item.item.discount_price %}
      <td>${{ order_item.get_total_discount_item_price }} &nbsp <span class="badge badge-primary">экономия ₽{{ order_item.get_amount_saved }}</span> </td>
      {% else %}
      <td>₽{{ order_item.get_total_item_price }}</td>
      {% endif %}
    </tr>
  {% endif %}
  {% endfor %}
  <tr>
    <td colspan="4"><b>Сумма заказа</b></td>
    <td>₽{{ objects.get_total }}</td>
  </tr>
  <tr>
  </tr>
  </tbody>
</table>
      <td colspan="4"><a href="/checkout/"</a><button type="button" class="btn btn-warning float-right">Перейти к оплате</button></td>
  <td colspan="4"><a href="/"</a><button type="button" class="btn btn-primary float-right">Продолжить покупки</button></td>
  {% else %}
  <h1>Корзина пуста</h1>
  {% endif %}
  <a href="/">Перейти на основную страницу</a>

  </main>
  <!--Main layout-->
</body>

{% endblock content %}

eshop_site/core/templates/payment.html
{% extends "base.html" %}
<h1>Ваш заказ был создан. Ждите звонка от оператора</h1>


{% block content %}
{% endblock content %}

eshop_site/core/templates/product.html
{% extends "base.html" %}
{% block content %}
  <!--Main layout-->
  <main class="mt-5">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <img src= {{object.image.url}} class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">
              <div class="mb-3">
                  <h1 class="lead font-weight-bold">{{ object.title }}</h1>
            </div>

            <div class="mb-3">
              <a href="">
                <span class="badge purple mr-1">{{ object.get_category_display }}</span>
              </a>
            </div>

            <p class="lead">
                {% if object.discount_price %}
                <del>₽{{ object.price }}</del>
                <span>₽{{ object.discount_price }}</span>
                {% else %}
                <span>₽{{ object.price }} </span>
                {% endif %}
            </p>

            <p class="lead font-weight-bold">Описание</p>

            <pre>{{ object.description}}</pre>

<!--            <form class="d-flex justify-content-left">-->
<!--              &lt;!&ndash; Default input &ndash;&gt;-->
<!--              <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">-->
<!--              <button class="btn btn-primary btn-md my-0 p" type="submit">Add to cart-->
<!--                <i class="fas fa-shopping-cart ml-1"></i>-->
<!--              </button>-->

<!--            </form>-->
            <a href="{{ object.get_add_to_cart_url }}" class="btn btn-primary btn-md my-0 p">Добавить в корзину
                <i class="fas fa-shopping-cart ml-1"></i>
            </a>
            <a href="{{ object.remove_from_cart_url }}" class="btn btn-danger btn-md my-0 p">Убрать из корзины
                <i class="fas fa-shopping-cart ml-1"></i>
            </a>

          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>





    </div>
  </main>
  <!--Main layout-->




{% endblock content %}

eshop_site/core/templates/scripts.html
{% load static %}

<script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
<!-- Initializations -->
<script type="text/javascript">
  // Animations initialization
  new WOW().init();

</script>